const games = [
{name:"Krunker", cat:"multiplayer", url:"https://krunker.io"},
{name:"1v1.LOL", cat:"action", url:"https://1v1.lol"},
{name:"Shell Shockers", cat:"multiplayer", url:"https://shellshock.io"},
{name:"Bloxd.io", cat:"multiplayer", url:"https://bloxd.io"},
{name:"Slow Roads", cat:"racing", url:"https://slowroads.io"},
{name:"2048", cat:"puzzle", url:"https://play2048.co"},
{name:"Chess", cat:"puzzle", url:"https://chess.com"},
{name:"Agar.io", cat:"multiplayer", url:"https://agar.io"},
{name:"Diep.io", cat:"action", url:"https://diep.io"},
{name:"Smash Karts", cat:"multiplayer", url:"https://smashkarts.io"},
{name:"Run 3", cat:"arcade", url:"https://run3.io"},
{name:"Paper.io 2", cat:"action", url:"https://paper-io.com"},
{name:"Tetris", cat:"puzzle", url:"https://tetris.com/play-tetris"},
{name:"Curve Rush", cat:"arcade", url:"https://curverush.io"},
{name:"Moto X3M", cat:"racing", url:"https://poki.com/en/g/moto-x3m"},
{name:"Stickman Hook", cat:"arcade", url:"https://poki.com/en/g/stickman-hook"},
{name:"Fireboy & Watergirl", cat:"puzzle", url:"https://poki.com/en/g/fireboy-and-watergirl-forest-temple"},
{name:"Subway Surfers", cat:"arcade", url:"https://poki.com/en/g/subway-surfers"},
{name:"Temple Run 2", cat:"arcade", url:"https://poki.com/en/g/temple-run-2"},
{name:"Slope 2", cat:"arcade", url:"https://slopegame.online"},
{name:"Vex 7", cat:"arcade", url:"https://poki.com/en/g/vex-7"},
{name:"Basket Random", cat:"sports", url:"https://poki.com/en/g/basket-random"},
{name:"Soccer Random", cat:"sports", url:"https://poki.com/en/g/soccer-random"},
{name:"Bitlife", cat:"simulation", url:"https://bitlifeonline.io"},
{name:"Minecraft Classic", cat:"sandbox", url:"https://classic.minecraft.net"},
{name:"Territorial.io", cat:"strategy", url:"https://territorial.io"},
{name:"Little Alchemy 2", cat:"puzzle", url:"https://littlealchemy2.com"},
{name:"Cookie Clicker", cat:"idle", url:"https://orteil.dashnet.org/cookieclicker"},
{name:"Zombs Royale", cat:"action", url:"https://zombsroyale.io"},
{name:"Krunker (alt)", cat:"multiplayer", url:"https://krunker.io"},
{name:"Mini Royale", cat:"action", url:"https://miniroyale.io"},
{name:"War Brokers", cat:"action", url:"https://warbrokers.io"},
{name:"Surviv.io", cat:"action", url:"https://surviv.io"},
{name:"Hole.io", cat:"arcade", url:"https://hole-io.com"},
{name:"Rocket Soccer Derby", cat:"sports", url:"https://poki.com/en/g/rocket-soccer-derby"},
{name:"Drift Hunters", cat:"racing", url:"https://drifthunters2.io"},
{name:"Madalin Stunt Cars 2", cat:"racing", url:"https://poki.com/en/g/madalin-stunt-cars-2"},
{name:"Basketball Stars", cat:"sports", url:"https://poki.com/en/g/basketball-stars"},
{name:"8 Ball Pool", cat:"sports", url:"https://8ballpool.com"},
{name:"Flip Master", cat:"arcade", url:"https://poki.com/en/g/flip-master"},
{name:"Duck Life", cat:"simulation", url:"https://poki.com/en/g/duck-life"},
{name:"Earn to Die", cat:"action", url:"https://poki.com/en/g/earn-to-die"},
{name:"World’s Hardest Game", cat:"arcade", url:"https://poki.com/en/g/worlds-hardest-game"},
{name:"Geometry Dash Lite", cat:"arcade", url:"https://poki.com/en/g/geometry-dash-lite"},
{name:"Tunnel Rush", cat:"arcade", url:"https://poki.com/en/g/tunnel-rush"},
{name:"Shell Shockers 2", cat:"multiplayer", url:"https://shellshock.io"},
{name:"Bloons TD 4", cat:"strategy", url:"https://ninjakiwi.com/Games/Tower-Defense/Bloons-Tower-Defense-4.html"},
{name:"Bloons TD 5", cat:"strategy", url:"https://ninjakiwi.com/Games/Tower-Defense/Bloons-Tower-Defense-5.html"}
];